name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  tests:
    name: Check syntax and installer
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh
      - name: Check syntax
        run: |
          for f in rc/*.zsh; do
            zsh -n "$f" || return 1
          done
      - name: Run installer
        run: |
          ZSH=$PWD zsh -c ". rc/install.zsh && install-zsh"
      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: run/zsh-install.sh
          if-no-files-found: error
      - name: Make a release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          title: Latest installer
          files: |
            run/zsh-install.sh
