name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  tests:
    name: Check syntax and installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh
      - name: Check syntax
        run: |
          for f in rc/*.zsh; do
            zsh -n "$f" || return 1
          done
      - name: Run installer
        run: |
          ZSH=$PWD zsh -c ". rc/install.zsh && install-zsh"
      - name: Upload installer
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: installer
          path: run/zsh-install.sh
          if-no-files-found: error
